var items = [
      [  10, 'a KEY', 1, 'KEY' ],
      [  11, 'an AXE', 1, 'AXE' ],
      [  12, 'STICKS', 1, 'STICKS' ],
      [  13, 'sheeplegs', 0, 'sheeplegs' ],
      [  14, 'MUSHROOMS', 1, 'MUSHROOMS' ],
      [  15, 'MONEY', 1, 'MONEY' ],
      [  16, 'a BARREL', 1, 'BARREL' ],
      [  17, 'a sheeptrunk', 0, 'sheeptrunk' ],
      [  18, 'BERRIES', 1, 'BERRIES' ],
      [  19, 'WOOL', 1, 'WOOL' ],
      [  20, 'a sheepskin', 0, 'sheepskin' ],
      [  21, 'a BAG', 1, 'BAG' ],
      [  22, 'a RAG', 1, 'RAG' ],
      [  23, 'a sheephead', 1, 'a sheephead' ],
      [  24, 'a SPADE', 1, 'SPADE' ],
      [  25, 'SULPHUR', 1, 'SULPHUR' ],
      [  26, 'a solid poison', 0, 'solid poison' ],
      [  27, 'a BUCKET', 1, 'BUCKET' ],
      [  28, 'TAR', 1, 'TAR' ],
      [  29, 'a liquid poison', 0, 'liquid poison' ],
      [  30, 'a dead dragon', 0, 'dead dragon' ],
      [  31, 'a STONE', 1, 'STONE' ],
      [  32, 'a FISH', 1, 'FISH' ],
      [  33, 'a KNIFE', 1, 'KNIFE' ],
      [  34, 'a DRAGONSKIN', 0, 'DRAGONSKIN' ],
      [  35, 'a dragonskin SHOES',1, 'SHOES' ],
      [  36, 'a PRIZE', 1, 'PRIZE' ],
      [  37, 'a SHEEP', 1, 'SHEEP' ]
]