var gameLocations = [
    gameLocation = { 'y': 0, 'x': 0, 'descr': 'You are inside a brimstone mine.', 'img': '11.gif', 'clr': 'rgb(235,211,64)', 'drc': ['EAST'] },
    gameLocation = { 'y': 0, 'x': 1, 'descr': 'You are at the entrance to the mine.', 'img': '12.gif', 'clr': 'rgb(89,93,87)', 'drc': ['EAST', 'WEST'] },
    gameLocation = { 'y': 0, 'x': 2, 'descr': 'A hill.', 'img': '13.gif', 'clr': 'rgb(117,237,243)', 'drc': ['EAST', 'WEST', 'SOUTH'] },
    gameLocation = { 'y': 0, 'x': 3, 'descr': 'Some bushes.', 'img': '14.gif', 'clr': 'rgb(202,230,51)', 'drc': ['EAST', 'WEST'] },
    gameLocation = { 'y': 0, 'x': 4, 'descr': 'An old deserted hut.', 'img': '15.gif', 'clr': 'rgb(220,204,61)', 'drc': ['EAST', 'WEST'] },
    gameLocation = { 'y': 0, 'x': 5, 'descr': 'The edge of a forest.', 'img': '16.gif', 'clr': 'rgb(167,245,63)', 'drc': ['EAST', 'WEST'] },
    gameLocation = { 'y': 0, 'x': 6, 'descr': 'A dark forest.', 'img': '17.gif', 'clr': 'rgb(140,253,99)', 'drc': ['WEST', 'SOUTH'] },
    //-----------------------------------------koniec wiersza 1------------------------------------------------------------------------
    gameLocation = { 'y': 1, 'x': 0, 'descr': 'A man nearby making tar.', 'img': '21.gif', 'clr': 'rgb(255,190,99)', 'drc': ['EAST', 'SOUTH'] },
    gameLocation = { 'y': 1, 'x': 1, 'descr': 'A timber yard.', 'img': '22.gif', 'clr': 'rgb(255,190,99)', 'drc': ['EAST', 'WEST', 'SOUTH'] },
    gameLocation = { 'y': 1, 'x': 2, 'descr': 'You are by a roadside shrine.', 'img': '23.gif', 'clr': 'rgb(167,245,63)', 'drc': ['NORTH', 'EAST', 'WEST', 'SOUTH'] },
    gameLocation = { 'y': 1, 'x': 3, 'descr': 'You are by a small chapel.', 'img': '24.gif', 'clr': 'rgb(212,229,36)', 'drc': ['EAST', 'WEST'] },
    gameLocation = { 'y': 1, 'x': 4, 'descr': 'You are on a road leading to a wood.', 'img': '25.gif', 'clr': 'rgb(167,245,63)', 'drc': ['EAST', 'WEST', 'SOUTH'] },
    gameLocation = { 'y': 1, 'x': 5, 'descr': 'You are in a forest.', 'img': '26 i 65.gif', 'clr': 'rgb(167,245,63)', 'drc': ['EAST', 'WEST'] },
    gameLocation = { 'y': 1, 'x': 6, 'descr': 'You are in a deep forest.', 'img': '27 i 67.gif', 'clr': 'rgb(140,253,99)', 'drc': ['NORTH', 'WEST'] },
    //-----------------------------------------koniec wiersza 2------------------------------------------------------------------------
    gameLocation = { 'y': 2, 'x': 0, 'descr': 'You are by the Vistula River.', 'img': '31.gif', 'clr': 'rgb(122,232,252)', 'drc': ['NORTH', 'EAST'] },
    gameLocation = { 'y': 2, 'x': 1, 'descr': 'You are by the Vistula River.', 'img': '32.gif', 'clr': 'rgb(140,214,255)', 'drc': ['NORTH', 'WEST'] },
    gameLocation = { 'y': 2, 'x': 2, 'descr': 'You are on a bridge over river.', 'img': '33.gif', 'clr': 'rgb(108,181,242)', 'drc': ['NORTH', 'SOUTH'] },
    gameLocation = { 'y': 2, 'x': 3, 'descr': 'You are by the old tavern.', 'img': '34.gif', 'clr': 'rgb(255,189,117)', 'drc': ['EAST'] },
    gameLocation = { 'y': 2, 'x': 4, 'descr': 'You are at the town\'s end.', 'img': '35.gif', 'clr': 'rgb(255,190,99)', 'drc': ['NORTH', 'WEST', 'SOUTH'] },
    gameLocation = { 'y': 2, 'x': 5, 'descr': 'You are in a butcher\'s shop.', 'img': '36.gif', 'clr': 'rgb(255,188,102)', 'drc': ['SOUTH'] },
    gameLocation = { 'y': 2, 'x': 6, 'descr': 'You are in a cooper\'s house.', 'img': '37.gif', 'clr': 'rgb(255,188,102)', 'drc': ['SOUTH'] },
    //-----------------------------------------koniec wiersza 3------------------------------------------------------------------------
    gameLocation = { 'y': 3, 'x': 0, 'descr': 'You are in the Wawel Castle.', 'img': '41.gif', 'clr': 'rgb(255,176,141)', 'drc': ['EAST'] },
    gameLocation = { 'y': 3, 'x': 1, 'descr': 'You are inside a dragon\'s cave.', 'img': '42.gif', 'clr': 'rgb(198,205,193)', 'drc': ['EAST', 'WEST'] },
    gameLocation = { 'y': 3, 'x': 2, 'descr': 'A perfect place to set a trap.', 'img': '43.gif', 'clr': 'rgb(255,176,141)', 'drc': ['NORTH', 'WEST'] },
    gameLocation = { 'y': 3, 'x': 3, 'descr': 'You are by the water mill.', 'img': '44.gif', 'clr': 'rgb(255,190,99)', 'drc': ['EAST'] },
    gameLocation = { 'y': 3, 'x': 4, 'descr': 'You are at a main crossroad.', 'img': '45.gif', 'clr': 'rgb(255,190,99)', 'drc': ['NORTH', 'EAST', 'WEST', 'SOUTH'] },
    gameLocation = { 'y': 3, 'x': 5, 'descr': 'You are on a town street.', 'img': '46.gif', 'clr': 'rgb(255,190,99)', 'drc': ['NORTH', 'EAST', 'WEST'] },
    gameLocation = { 'y': 3, 'x': 6, 'descr': 'You are in a frontyard of your house.', 'img': '47.gif', 'clr': 'rgb(255,190,99)', 'drc': ['NORTH', 'WEST', 'SOUTH'] },
    //-----------------------------------------koniec wiersza 4------------------------------------------------------------------------
    gameLocation = { 'y': 4, 'x': 0, 'descr': '', 'img': '', 'clr': '', 'drc': [] },
    gameLocation = { 'y': 4, 'x': 1, 'descr': '', 'img': '', 'clr': '', 'drc': [] },
    gameLocation = { 'y': 4, 'x': 2, 'descr': '', 'img': '', 'clr': '', 'drc': [] },
    gameLocation = { 'y': 4, 'x': 3, 'descr': 'You are by a swift stream.', 'img': '54.gif', 'clr': 'rgb(108,181,242)', 'drc': ['EAST'] },
    gameLocation = { 'y': 4, 'x': 4, 'descr': 'You are on a street leading forest.', 'img': '55.gif', 'clr': 'rgb(255,190,99)', 'drc': ['NORTH', 'WEST', 'SOUTH'] },
    gameLocation = { 'y': 4, 'x': 5, 'descr': 'You are in a woodcutter\'s backyard.', 'img': '56.gif', 'clr': 'rgb(255,190,99)', 'drc': ['SOUTH'] },
    gameLocation = { 'y': 4, 'x': 6, 'descr': 'You are in a shoemaker\'s house.', 'img': '57.gif', 'clr': 'rgb(254,194,97)', 'drc': ['NORTH'] },
    //-----------------------------------------koniec wiersza 5------------------------------------------------------------------------
    gameLocation = { 'y': 5, 'x': 0, 'descr': '', 'img': '', 'clr': '', 'drc': [] },
    gameLocation = { 'y': 5, 'x': 1, 'descr': '', 'img': '', 'clr': '', 'drc': [] },
    gameLocation = { 'y': 5, 'x': 2, 'descr': '', 'img': '', 'clr': '', 'drc': [] },
    gameLocation = { 'y': 5, 'x': 3, 'descr': 'You are in a bleak funeral house.', 'img': '64.gif', 'clr': 'rgb(254,194,97)', 'drc': ['EAST'] },
    gameLocation = { 'y': 5, 'x': 4, 'descr': 'You are on a path leading to the wood.', 'img': '26 i 65.gif', 'clr': 'rgb(167,245,63)', 'drc': ['NORTH', 'EAST', 'WEST'] },
    gameLocation = { 'y': 5, 'x': 5, 'descr': 'You are at the edge of a forest.', 'img': '66.gif', 'clr': 'rgb(167,245,63)', 'drc': ['NORTH', 'EAST', 'WEST'] },
    gameLocation = { 'y': 5, 'x': 6, 'descr': 'You are in a deep forest.', 'img': '27 i 67.gif', 'clr': 'rgb(140,253,99)', 'drc': ['WEST'] }
]